### ISSUE TITLE
user status (online, offline, busy)

### ISSUE THREAD

**Issue by jasjs1** [jasjs1/Programmer-Netlink#66]
- [x] selector
- [x] button selector styling
- [ ] save status to localsotrage
- [ ] display on profile
- [ ] ability to click on status and then the status settings thing shows

**Comment by jSagvold28** [comment]
Online: This status indicates that the user is currently active and available on the platform.

Offline: This status indicates that the user is not currently active on the platform and is not available for communication.

Away: This status indicates that the user is not currently active on the platform, but they may still be available for communication. This status is useful for situations where a user may be temporarily unavailable, such as taking a break or stepping away from their device for a short time.

Do Not Disturb: This status indicates that the user is currently active on the platform, but they do not want to be disturbed. This status is useful when a user is busy and does not want to be interrupted, such as when they are in a meeting or focusing on a task.

Busy: This status indicates that the user is currently active on the platform, but they are occupied with another task or conversation. This status is useful when a user is multitasking and may not be able to respond immediately.

Invisible: This status indicates that the user is currently active on the platform, but they have chosen to appear as offline to other users. This status is useful for users who want to use the platform without being disturbed or seen by others.
